### ISSUE TITLE
Crash on 'Edit Message'

### ISSUE THREAD

**Issue by thorsager** [thorsager/t-slacker#21]
The whole client crashes if a message gets edited.

**Comment by thorsager** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1328dc4]
goroutine 133 [running]:
github.com/thorsager/t-slacker/runtime.(*AppRuntime).renderMessageEvent(0xc00014c280, 0xc00009c280, 0x9, 0xc0000e2000, 0x1d)
    /Users/mit/go/src/github.com/thorsager/t-slacker/runtime/messages.go:30 +0x104
github.com/thorsager/t-slacker/runtime.(*AppRuntime).rtmEvent(0xc00014c280, 0xc0000ac6c0, 0xc00000e140)
    /Users/mit/go/src/github.com/thorsager/t-slacker/runtime/app_context.go:159 +0x39e
github.com/thorsager/t-slacker/connection.(*Connection).delegateEvents(0xc0000ac6c0)
    /Users/mit/go/src/github.com/thorsager/t-slacker/connection/slack.go:193 +0x3a
created by github.com/thorsager/t-slacker/connection.New
    /Users/mit/go/src/github.com/thorsager/t-slacker/connection/slack.go:184 +0x541
```
