### ISSUE TITLE
Panic on "link only message"

### ISSUE THREAD

**Issue by thorsager** [thorsager/t-slacker#6]
When receiving a link only message, t-slacker panics due to a `nil` pointer 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1328c0b]
goroutine 6 [running]:
	github.com/thorsager/t-slacker/runtime.(*AppRuntime).renderMessageEvent(0xc000144280, 0xc000762500, 0x9, 0xc0004f6160, 0x13a1640)
		/Users/mit/go/src/github.com/thorsager/t-slacker/runtime/messages.go:27 +0xcb
	github.com/thorsager/t-slacker/runtime.(*AppRuntime).rtmEvent(0xc000144280, 0xc0004cc240, 0xc000494220)
		/Users/mit/go/src/github.com/thorsager/t-slacker/runtime/app_context.go:153 +0x2a9
	github.com/thorsager/t-slacker/connection.(*Connection).delegateEvents(0xc0004cc240)
		/Users/mit/go/src/github.com/thorsager/t-slacker/connection/slack.go:193 +0x3a 
created by github.com/thorsager/t-slacker/connection.New
	/Users/mit/go/src/github.com/thorsager/t-slacker/connection/slack.go:184 +0x541
```

**Comment by thorsager** [comment]
It would seam that this was also fixed by changes made in #21
